turtlebot3: #namespace

    task_and_robot_environment_name: 'TurtleBot3World-v0'
    ros_ws_abspath: "/home/simon/PathFinderRL/thesis_ws"
    running_step: 0.04 # amount of time the control will be executed
    pos_step: 0.016     # increment in position for each command
    
    #dqn parameters
    gamma: 0.99
    epsilon_start: 1.0
    epsilon_end: 0.1
    epsilon_decay: 40000
    n_episodes: 5000
    target_update: 10
    batch_size: 128

    running_step: 0.06 # Time for each step

    load_model: true # specifies if we want to load a model or start training from scratch
    reset_epsilon: false # specifies if we want to reset the epsilon value when loading a model
    reset_memory: false # specifies if we want to reset the memory when loading a model

    alpha: 0.6
    beta_start: 0.4
    beta_frames: 250000

    tau: 0.001
    use_soft_update: true

    elite_ratio: 0.2
    reward_threshold: 100