turtlebot3: #namespace

    task_and_robot_environment_name: 'TurtleBot3World-v0'
    ros_ws_abspath: "/home/simon/PathFinderRL/thesis_ws"
    running_step: 0.04 # amount of time the control will be executed
    pos_step: 0.016     # increment in position for each command
    
    #dqn parameters
    gamma: 0.97
    epsilon_start: 0.95
    epsilon_end: 0.05
    epsilon_decay: 30000
    n_episodes: 10000
    target_update: 50
    batch_size: 256 # maybe increase to 256

    running_step: 0.06 # Time for each step

    load_model: false   # specifies if we want to load a model or start training from scratch
    reset_epsilon: false # specifies if we want to reset the epsilon value when loading a model

    epsilon_warmup_steps: 5000
    epsilon_decay_steps: 30000